### ISSUE TITLE
유저 채권 등록 API 추가

### ISSUE THREAD

**Issue by DavidKim22** [yunut/securities_api#15]
유저의 채권 투자 히스토리 등록하는 API 추가

**Comment by yunut** [comment]
채권 등록 시, 이전 회의했던대로 다음과 같은 플로우가 필요합니다. 메모해둘게요

1. 채권 등록은 정확한 이름으로 해야하기에 리스트 제공 후, 리스트를 클릭하면 그 채권을 저장하는 방식으로 진행해야 할듯 합니다.

2. 텔레그램에서 유저 채팅방을 DB에 쌓기 위해서 어떻게 진행되는지 히스토리 파악이 필요합니다.

**Comment by DavidKim22** [comment]
채권이름이 현재는 전체를 긁어오는데 지금 방식의 문제점으로 판단되는게 뒤에 채권 옵션들이 붙어있는 것이라고 생각합니다

이 부분을 따로 컬럼을 빼서 처리하는게 어떨까 싶기는 한데 일단은 기본적인 텔레그램과 연동하는 api부터 만들겠습니다

**Comment by yunut** [comment]
음 플로우부터 먼저 확정하는게 우선일듯 해요

어떤 플로우로 진행하시려 하는지 대략적으로 알수 있을까요 ?
